"""create initial models

Revision ID: 8b437a181776
Revises: f114b2fb7732
Create Date: 2026-07-06 14:19:55.690818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b437a181776'
down_revision: Union[str, Sequence[str], None] = 'f114b2fb7732'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=True),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('years_of_experience', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('english_level', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('desired_salary_min', sa.Integer(), nullable=True),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('position_title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('work_format', sa.String(length=100), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('source_type', sa.String(length=100), server_default='manual_text', nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracked_vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_profile_id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), server_default='saved', nullable=False),
    sa.Column('priority', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_contact_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_action_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancy_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vacancy_id', sa.Integer(), nullable=False),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('english_level', sa.String(length=100), nullable=True),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('optional_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('responsibilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('green_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.String(length=100), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('generated_contents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_vacancy_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('prompt_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_text', sa.Text(), nullable=False),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_vacancy_id'], ['tracked_vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_vacancy_id', sa.Integer(), nullable=False),
    sa.Column('interaction_type', sa.String(length=100), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_vacancy_id'], ['tracked_vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tracked_vacancy_id', sa.Integer(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('recommendation', sa.String(length=100), nullable=True),
    sa.Column('strong_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('partial_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('missing_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_points', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reasoning_summary', sa.Text(), nullable=True),
    sa.Column('ai_model', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracked_vacancy_id'], ['tracked_vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resume_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_document_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['resume_document_id'], ['resume_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resume_sections')
    op.drop_table('match_analyses')
    op.drop_table('interactions')
    op.drop_table('generated_contents')
    op.drop_table('vacancy_analyses')
    op.drop_table('tracked_vacancies')
    op.drop_table('resume_documents')
    op.drop_table('vacancies')
    op.drop_table('candidate_profiles')
    # ### end Alembic commands ###
