"""add unique constraint to tracked vacancies

Revision ID: a44639bbaa8f
Revises: 6607c21f834f
Create Date: 2026-07-09 17:12:22.040508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a44639bbaa8f'
down_revision: Union[str, Sequence[str], None] = '6607c21f834f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_tracked_vacancies_resume_document_id_vacancy_id', 'tracked_vacancies', ['resume_document_id', 'vacancy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tracked_vacancies_resume_document_id_vacancy_id', 'tracked_vacancies', type_='unique')
    # ### end Alembic commands ###
