"""add unique constraint to match analyses

Revision ID: e626b56b02d1
Revises: a44639bbaa8f
Create Date: 2026-07-09 21:12:53.856750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e626b56b02d1'
down_revision: Union[str, Sequence[str], None] = 'a44639bbaa8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_match_analyses_tracked_vacancy_id', 'match_analyses', ['tracked_vacancy_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_match_analyses_tracked_vacancy_id', 'match_analyses', type_='unique')
    # ### end Alembic commands ###
